// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_request.proto

package com.grpc.client.service;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   * @return The userId.
   */
  int getUserId();
}
