// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.grpc.grpcserver.service;

public final class UserServiceOuterClass {
  private UserServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022user_service.proto\032\022user_request.proto" +
      "\032\023user_response.proto25\n\013UserService\022&\n\007" +
      "getUser\022\014.UserRequest\032\r.UserResponseB\037\n\033" +
      "com.grpc.grpcserver.serviceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.grpc.grpcserver.service.UserRequestOuterClass.getDescriptor(),
          com.grpc.grpcserver.service.UserResponseOuterClass.getDescriptor(),
        });
    com.grpc.grpcserver.service.UserRequestOuterClass.getDescriptor();
    com.grpc.grpcserver.service.UserResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
